@startuml
'https://plantuml.com/component-diagram

[Core]

[Common]

[Player]

[CollisionSystem]

[CommonProjectile]
[Projectile]

[CommonWeapon]
[Weapon]

[CommonEnemy]

[Enemy]

[CommonAI]
[AI]

[Inventory]

[CommonItem]

@enduml
